version: '3.8'

services:
  nestapp:
    image: lyen33/nest-cnp3:1.0
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    networks:
      - cnp3-net

  mongo:
    image: mongo:4.4
    restart: always
    deploy:
      replicas: 1
    volumes:
      - mongo_data:/data/db
    networks:
      - cnp3-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfssrv01,rw"
      device: ":/data/docker-vols/group10/mongo_data"

networks:
  cnp3-net:
    driver: overlay
